### ISSUE TITLE
playerjoin event is disable on 1.18.1 paper

### ISSUE THREAD

**Issue by SnowSwordScholar** [Puharesource/TitleManager#448]
**Describe the bug**
When I update the sever to 1.18
I find the bug 
sometims it can work well
but in many times it can't make it

**Screenshots**
![Screenshot_2022-03-04-17-30-32-02_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/73566969/156737909-2795211c-6743-4a7c-b696-bc5f72377bdd.png)

**Server information:**
 - TitleManager version: 2.3.6
 - Spigot version: Paper1.18.1]

**Additional context**

My English is too terrible to provid more information
sorry

**Comment by AntZaro** [comment]
I am having this same error message whenever anyone joins the server. Yet, the greeting hologram seems to work fine.

Running on 1.18.2. Happy to provide any other details if needed.

**Comment by ItsDanielle** [comment]
Having the same issue. Running Paper 1.18.1 with latest version.

`[20:31:46 ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.3.6
java.lang.NoClassDefFoundError: Could not initialize class io.puharesource.mc.titlemanager.internal.reflections.ReflectionPlayerExtensionsKt
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$createPlaceholder$1.getText(PlaceholderServiceText.kt:183) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText.replaceText(PlaceholderServiceText.kt:152) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setFooter(PlayerListServiceSpigot.kt:156) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:101) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:100) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:90) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:60) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedFooter(PlayerListServiceSpigot.kt:171) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedHeaderAndFooter(PlayerListServiceSpigot.kt:198) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:212) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:95) ~[TitleManager-2.3.6 (2).jar:?]
        at io.puharesource.mc.titlemanager.internal.model.event.TMEventListener._init_$lambda-1(TMEventListener.kt:31) ~[TitleManager-2.3.6 (2).jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-198]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:305) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-198]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by WMK965** [comment]
Well I met the same problem,so I have to disable it temporarily.
btw，有什么同功能插件吗？
